# -*- coding: utf-8 -*-
"""Real-Time ICU Patient Vital Monitoring & Early Risk Alert System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0wASQSqJO8CzkAoXT6hstlLaY48vyoA
"""

!pip install rx pandas plotly

"""**Step 1: Simulate Real-Time Patient Vitals**"""

import rx
from rx import operators as ops
import random
import datetime
import time

def vitals_generator():
    while True:
        yield {
            "time": datetime.datetime.now().strftime("%H:%M:%S"),
            "heart_rate": random.randint(55, 130),
            "spo2": random.randint(85, 100),
            "bp": random.randint(85, 160)
        }

"""**Step 2: Create Real-Time Stream**"""

source = rx.from_iterable(vitals_generator()).pipe(
    ops.take(25)
)

"""**Step 3: Detect Critical Conditions (ALERT ENGINE)**"""

alerts = source.pipe(
    ops.filter(lambda v: v["heart_rate"] > 120 or v["spo2"] < 90 or v["bp"] > 150),
    ops.map(lambda v:
        f"🚨 ALERT | Time: {v['time']} | HR: {v['heart_rate']} | SpO2: {v['spo2']} | BP: {v['bp']}"
    )
)

print("🔍 Monitoring ICU Patient...")
print("-"*45)

alerts.subscribe(
    on_next=lambda msg: print(msg),
    on_completed=lambda: print("\nMonitoring Complete.")
)

"""**Step 4: Batch Analytics (Average vitals every 5 readings)**"""

source.pipe(
    ops.buffer_with_count(5)
).subscribe(
    on_next=lambda batch: print(
        f"📊 Batch Avg HR: {sum(v['heart_rate'] for v in batch)/5:.1f}"
    )
)

"""**Step 5: Live ICU Dashboard (Visualization)**"""

import plotly.graph_objects as go
import pandas as pd
from IPython.display import display, clear_output

vital_gen = vitals_generator()
df = pd.DataFrame(columns=["Time", "HeartRate"])

fig = go.Figure()
fig.add_trace(go.Scatter(x=[], y=[], mode="lines+markers"))
fig.update_layout(
    title="Live ICU Heart Rate Monitoring",
    xaxis_title="Time",
    yaxis_title="Heart Rate (BPM)",
    template="plotly_dark"
)

print("📈 Launching Live ICU Dashboard...")

for _ in range(25):
    data = next(vital_gen)
    df = pd.concat([df, pd.DataFrame(
        {"Time": [data["time"]], "HeartRate": [data["heart_rate"]]}
    )]).tail(15)

    with fig.batch_update():
        fig.data[0].x = df["Time"]
        fig.data[0].y = df["HeartRate"]
        fig.data[0].marker.color = [
            "red" if hr > 120 else "#00cc96" for hr in df["HeartRate"]
        ]

    clear_output(wait=True)
    display(fig)
    time.sleep(1)